### ISSUE TITLE
Determination of Model Stabilization

### ISSUE THREAD

**Issue by rahul1525** [RHESSys/RHESSys#101]
I have been spinning up a rhessys model for 600 years.

Here are some doubts which I went through.

1. First, I am not sure when the spinup process should be declared "STABLE".
As written in the RHESSys Manual- "The model may be considered stable when the plant and soil C and N variables are not trending up or down". Here my doubt is "trending up or down????"; all the series (plantc, plantn, soilc,soiln) are decreasing continuously.

2. Second doubt is going in this way I am not sure where to stop the process as it is decreasing continuously.
3. Another observation is that, I found negative values in case of plantc starting at around 425th year and continue decreasing again.

I am attaching the results of spinup process and also the results for various spinup year regarding the Plant and Soil C and N are also appended in the same file.

Can anyone clear my doubts???????
Your help will be wholeheartedly appreciated.
Thanks in advance.

[spin 2004.xlsx](https://github.com/RHESSys/RHESSys/files/579979/spin.2004.xlsx)

**Comment by jschoate** [comment]
we look at soil stabilization to be when soil C/N reach a steady/stable state, i.e. not fluctuating more than 5%. for example, look at the fluctuation of your soil N for the last 10-15 years.

how did you initialize your model? are you allowing soil and vegetation to develop simultaneously? i.e. are you starting soil and veg C & N stores at 0 and allowing RHESSys to grow the vegetation? or are you starting your model at some starting value of C & N for either soil or veg or both?

must consider the starting point of your model, the def files being used for soil/veg, and how those are co-evolving.
