### ISSUE TITLE
GRASS6.4 Problem of installation and Running

### ISSUE THREAD

**Issue by xialang2012** [RHESSys/RHESSys#115]
It seems that GRASS6.4 is no longer available for Ubuntu16.04, (https://launchpad.net/~grass/+archive/ubuntu/grass-stable), and for version high than 6.4, e.g. 7.4, it does not work,

> In file included from src/grassio.c:3:0:
> include/grassio.h:4:23: fatal error: grass/gis.h: No such file or directory
> compilation terminated.
> makefile:53: recipe for target 'objects/grassio.o' failed
> make[1]: *** [objects/grassio.o] Error 1
> make[1]: Leaving directory '/home/xl/RHESSys/cf'
> makefile:15: recipe for target 'default' failed
> make: *** [default] Error 2

So, how can I install it correctly?

**Comment by xialang2012** [comment]
Report here. 
One should use Ubuntu 14 to run it. 
The test data for version 6.0 is not ready, version of 5.2 can run well.

**Comment by xialang2012** [comment]
I am reopening it.
More detailed about the failed test on version 6.4

```
# Run Python-based functional testing
RHESSYS_BIN=rhessys6.0  python -m unittest discover -s test

WARNING
Reading world file header from legacy world file.
This feature will be removed from a future release.
Please re-run g2w to generate a separate world file header.
WARNING

Reading ../defs/basin.def
Reading ../defs/hill.def
Reading ../defs/zone.def
Reading ../defs/soil_sandyloam.def

Note that soil depth used for biogeochem cycling (active zone z)
is more than 0.5 meter different from hydrologic soil depth
for soil default file: ../defs/soil_sandyloam.def
Reading ../defs/lu_undev.def
Reading ../defs/veg_douglasfir.def

Constructed fire defaults

Constructing base stations
 Reading Base station 101
 Non critical sequences 0
 Reading from 101 hja_prime_hourly   
 Finished constructing base stations

 Constructing world 1

 Constructing basins

No parameter value found for basin_parm_ID and 'useDefault' flag set to false

FATAL ERROR: in construct_basin,basin default ID 79 not found.
E
======================================================================
ERROR: setUpClass (test_mass_balance.TestWaterBalance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xl/RHESSys/rhessys/test/test_mass_balance.py", line 49, in setUpClass
    (testsite['name'], cmdline, runDir) )
Exception: Failed to run RHESSys for test site W8, command: /home/xl/RHESSys/rhessys/rhessys6.0 -t ../tecfiles/tec.testcase -w ../worldfiles/world.w8.testcase  -r ../flowtables/flow.w8  -st 2003 10 1 1 -ed 2007 10 1 1 -pre ../out/testcase -s 0.812 58.038 -sv 0.812 58.038 -gw 0.042 0.716 -g -b, cwd: /home/xl/RHESSys/rhessys/test/data/testtmp/W8/scripts

----------------------------------------------------------------------
Ran 0 tests in 0.031s

FAILED (errors=1)
make: *** [functest] Error 1

```

I used the ./travis.sh command to run it. For version 5.2, it was ok.

**Comment by jschoate** [comment]
If you are still having this issue - if the reason you are attempting to install GRASS is in order to use the GRASS/RHESSys interface programs g2w and cf in order to create the worldfile/flowtable - 
you no longer need to use those programs to create worldfile/flowtable.
you can now use the R RHESSysPreprocessing package to create your worldfile/flowtable - which means you can use any GIS you want and export your raster maps as geotiffs or ascii files for use with the RHESSysPreprocessing package in R. see instructions here:https://github.com/RHESSys/RHESSys/wiki/Worldfile#rhessys-preprocessing-in-r

**Comment by xialang2012** [comment]
Hi, @jschoate I have succeeded built it on window and Linux. Thanks for your reply.  

By the way, could you tell me about how to create *.defs files which located in 'defs' folder? Especially the def for soil.def. I am now trying to create the def file for soil. Thanks.

**Comment by jschoate** [comment]
There is a parameter database that you can generate def files from - it contains a library of commonly used soil and veg def files. you can access it here: https://github.com/RHESSys/ParamDB
scroll down below the code files to see the instructions on using it.
in the mean time - i've attached a def file for the soil type sandyloam, and you can find information on def file contents here: https://github.com/RHESSys/RHESSys/wiki/Parameter-Definition-Files
[SoilSandyloamDef.txt](https://github.com/RHESSys/RHESSys/files/2857052/SoilSandyloamDef.txt)

**Comment by xialang2012** [comment]
Thanks for your reply. I got it.
