### ISSUE TITLE
Image of an annotated template

### ISSUE THREAD

**Issue by jschoate** [RHESSys/RHESSys#118]
[Annotated_Template.pdf](https://github.com/RHESSys/RHESSys/files/2790415/Annotated_Template.pdf)

**Comment by jschoate** [comment]
![anntemplate1](https://user-images.githubusercontent.com/3721146/51659336-0c495f00-1f5f-11e9-8534-88112d40ede3.jpg)
![anntemplate2](https://user-images.githubusercontent.com/3721146/51659437-50d4fa80-1f5f-11e9-8064-d1fac049a382.jpg)
![anntemplate3](https://user-images.githubusercontent.com/3721146/51659444-56324500-1f5f-11e9-9923-ec7dcce7139a.jpg)

**Comment by xialang2012** [comment]
Thanks.
