### ISSUE TITLE
Generating input_dated_seq_list to run Rhessys from R

### ISSUE THREAD

**Issue by magonsa** [RHESSys/RHESSys#127]
Hi, I'm trying to generate the climatic sequence inputs to use RHESSysIOinR but I keep geting this message: FATAL ERROR: in construct_clim_sequence end date beyond end of clim sequence. I'm using the vignette from here: https://rdrr.io/github/RHESSys/RHESSysIOinR/src/vignettes/sample_inputs_simple.R, and the data from the study cases uploaded here in GitHub. Can anyone help me to generate the climatic inputs?
Thank you!

**Comment by wburke24** [comment]
Hi - This may be a result of changes I've made, I've been changing a bunch of those helper functions and haven't made an up to date example script, my apologies. Take a look at the sample_inputs.R vignette to see the more basic version (with the inputs the run_rhessys fully written out), and also make sure your climate base station and inputs are set up correctly: https://github.com/RHESSys/RHESSys/wiki/Climate-Inputs.

**Comment by magonsa** [comment]
Hi, Thanks so much! I solved the problem by using a more basic version as you suggested. Thanks!
Unfortunately now I'm getting this error: FATAL ERROR: in construct_basin,basin default ID 79 not found. I'll open another issue.
Thank you very much.
