### ISSUE TITLE
Could not find hillslope 1460 in  basin 1. Skipping hillslope...

### ISSUE THREAD

**Issue by Benxin1997** [RHESSys/RHESSys#138]
Hi guys, got some troubles here. I was running RHESSys 7.2, and it went well until I met "Could not find hillslope 1460 in  basin 1. Skipping hillslope..."

> Constructing base stations
>  Reading Base station 101
>  Non critical sequences 0
>  Reading from 101 hja_prime_hourly   
>  Finished constructing base stations
> 
>  Constructing world 1
>  Constructing basins
>  Creating basin 0
> 
>  Reading hillslope 0
> 
>  Construction zone 0
>  Construction zone 1
>  Construction zone 2
>  Construction zone 3
>  Construction zone 4
>  Construction zone 5
>  Construction zone 6
>  Construction zone 7
>  Construction zone 8
>  Construction zone 9
> ....
> Reading hillslope 6
> 
> Construction zone 0
> ...
> Hillslopes complete
> Could not find hillslope 1460 in  basin 1. Skipping hillslope...
> Segmentation fault (core dumped)

Attached are the worldfile and template file.

I checked this bug message in rhessys code, and I found it from "find_hillslope_in_basin.c". 
My worldfile contains 7 hillslopes,  I am wondering why it reads hillslope_ID as 1460, and 1460 happens to be the number of total patches. Does anyone know how to solve it? Thank you!

[spinuptest.world.txt](https://github.com/RHESSys/RHESSys/files/6043236/spinuptest.world.txt)
[template.txt](https://github.com/RHESSys/RHESSys/files/6043241/template.txt)

**Comment by renjianning** [comment]
The problem may be because of your flowtable, you need to check the format
of flow table
the first two lines should like this:
24 (number of hillslopes)
144 216 (hillslope_ID, number of patches inside of that hillslope)

**Comment by Benxin1997** [comment]
That's exactly the point! I used the old version of flowtable, after converting it to be compatible with version 7.0, it works just fine. Thank you Dr.Ren, and happy Lantern Festival!
