### ISSUE TITLE
Is In stream routing compatible with RHESSys7.2？

### ISSUE THREAD

**Issue by Benxin1997** [RHESSys/RHESSys#141]
Hi, I would like to apply RHESSys to a relatively big watershed (area of about 16000 km2), thus stream routing needs to be considered. However, I doubt whether **In stream routing** is compatible with RHESSys 6.0 and later versions (looks like the stream routing file can be only made on GRASS instead of R. If not, is it necessary to switch to rhessys5.14 for compatibility?

Thank you

**Comment by jschoate** [comment]
Currently we are working to upgrade in-stream routing in R for compatibility with the new version of RHESSys - and will make new tools available in the next few months. You can still create the streamtable with the GRASS interface program cst - which will be compatible with RHESSys6 and earlier. There is a format change to the flowtable/streamtable in RHESSys7. There were some changes to the worldfile in RHESSys6 - but there a some easy methods to make your worldfile compatible. 
https://github.com/RHESSys/RHESSys/wiki/RHESSys6.0-new-functionality
https://github.com/RHESSys/RHESSys/wiki/RHESSys6.0-new-functionality#worldfile-read-by-tag---required-for-use-with-rhessys60
https://github.com/RHESSys/RHESSys/wiki/RHESSys6.0-new-functionality#transform-worldfile

**Comment by Benxin1997** [comment]
Got it, thanks!
