### ISSUE TITLE
Segmentation fault (core dumped) - Constructing Basins

### ISSUE THREAD

**Issue by CQuin042** [RHESSys/RHESSys#145]
RHESSys 7.1 on a Ubuntu 14.04 VM

Issue was present when running with own data and with test data. Test data worldfile and climate base file have been modified to locate definition, and climate files as well as modified to run RHESSys 7.1. 

Error message attached below

-

ubuntu14@ubuntu14-VirtualBox:~/RHESSys/bin$ rhessys7.1 -t tecfiles/tec.testcase -w worldfiles/world.w8.testcase  -r flowtables/flow.w8  -st 2003 10 1 1 -ed 2007 10 1 1 -pre out/w8.testcase -s 0.812 58.038 -sv 0.812 58.038 -gw 0.042 0.716 -g -b

WARNING
Reading world file header from legacy world file.
This feature will be removed from a future release.
Please re-run g2w to generate a separate world file header.
WARNING

Reading defs/basin.def
Reading defs/hill.def
Reading defs/zone.def
Reading defs/soil_sandyloam.def

Note that soil depth used for biogeochem cycling (active zone z)
is more than 0.5 meter different from hydrologic soil depth
for soil default file: defs/soil_sandyloam.def
Reading defs/lu_undev.def
Reading defs/veg_douglasfir.def

using 0.100000 0.100000 for sunlit shade flnr and 0.006000 and 0.006000 for sun and shade gl_max

Constructed fire defaults

Constructing base stations
 Reading Base station 101
 Non critical sequences 0
 Reading from 101 hja_prime_hourly   
 Finished constructing base stations

 Constructing world 1

 Constructing basins

 creating basin 0
num_variables=17,paramCnt=18, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=19, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=20, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=21, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=22, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=23, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=24, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=25, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=26, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=27, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=28, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=29, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=30, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=31, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=32, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=33, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=34, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=35, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=36, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=37, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=38, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=39, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=40, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=41, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=42, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=43, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=44, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=45, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=46, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=47, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=48, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=49, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=50, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=51, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=52, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=53, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=54, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=55, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=56, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=57, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=58, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=59, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=60, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=61, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=62, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=63, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=64, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=65, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=66, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=67, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=68, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=69, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=70, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=71, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=72, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=73, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=74, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=75, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=76, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=77, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=78, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=79, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=80, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=81, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=82, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=83, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=84, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=85, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=86, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=87, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=88, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
num_variables=17,paramCnt=89, in level Basin
added new parameter, adjust the num_variables in phys_constants.h
Segmentation fault (core dumped)

-

**Comment by yuefeng-98** [comment]
hi!
I meet the same problem with you.
Could you please tell me how to solve this one?
Thank you so much!

**Comment by CQuin042** [comment]
My issue happened because I did not use a mask to mask my basin from the DEM before constructing the flow tables. A mask must be applied before creating flow table so that only the watershed is selected in the DEM. 

I hope this helps.

**Comment by yuefeng-98** [comment]
I am really glad to receive your reply, it will help me a lot ! Meanwhile, I am so sorry to write you this e-mail so late, because I am busy with my final exams and homework, so that forget to check my e-mail. 


Here's the problem I had meet: "Run functional tests for RHESSys"
I use VMware Workstation16.1.1, ubuntu 18.04.6, and RHESSys7.3.

Please forgive me if I am bothering you. If you could reply I would be honored and lucky if you could reply!













At 2021-11-29 22:33:07, "CQuin042" ***@***.***> wrote:

My issue happened because I did not use a mask to mask my basin from the DEM before constructing the flow tables. A mask must be applied before creating flow table so that only the watershed is selected in the DEM.

I hope this helps.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by baijiayihhh** [comment]
> My issue happened because I did not use a mask to mask my basin from the DEM before constructing the flow tables. A mask must be applied before creating flow table so that only the watershed is selected in the DEM.
> 
> I hope this helps.

hello,Can you please explain the MASK operation, because I'm very confused, it's applied immediately after importing the dem map in GRASS GIS.
g.copy rast=dem1000,MASK? After that, all the operations to generate slope and basin will use the generated MASK to get ？
