### ISSUE TITLE
Patch Scale Output for Multiple Patches

### ISSUE THREAD

**Issue by CQuin042** [RHESSys/RHESSys#157]
I would like to generate patch scale outputs for more than one patch within the watershed being processed. 

the documented -p basin_ID hillslope_ID zone_ID patch_ID works for patch output for a single patch but -p basin_ID hillslope_ID zone_ID patch_ID -p basin_ID hillslope_ID zone_ID patch_ID does not seem to work for two patches. 

How can a set number of patches be output so that they may be used for calibration?

**Comment by jschoate** [comment]
Use the [Output filter](https://github.com/RHESSys/RHESSys/wiki/Output-Filtering) capability instead of standard/legacy RHESSys output

**Comment by CQuin042** [comment]
Thank you for the solution. I am unable to utilize the output filter in R by inputting my own output filter or by using the included "p301h2_filter.yml" file. 

The error that occurs is 
"Error: syntax error, unexpected DOT, expecting PATH_SPEC or FILENAME_SPEC, for token: |.|
construct_output_filter failed with error: output_filter_parser returned with an error."

The token may change depending on the output path chosen but the error persists.

RHESSys 7.4 is being utilized

**Comment by CQuin042** [comment]
The issue has been resolved by updating to the most recent version of RHESSysIOinR. Thank you for the suggestion to use the output filter capability.
