### ISSUE TITLE
add Linux capability to g2w/AverageTables_Unix/makefile

### ISSUE THREAD

**Issue by trel** [RHESSys/RHESSys#2]
rat wasn't building on Linux - worked with mac

**Comment by LuckyanTan** [comment]
Hello,
      I am installing RHESSys on Linux. When I was compiling rat file in AverageTables_Unix folder, some warnings occurred.
 i.e. 
      makefile: 36: warning: overriding commands for target 'install'
      makefile: 27: warning: ignoring old commands for target 'install'

I thus removed the last 2 lines in the makefile (i.e. install:  cp $(PGM) $(RHESSYS_BIN)). am I doing something wrong?

The modified makefile in the  AverageTables_Unix folder is displayed below: 

PGM = rat
CC  = gcc 
RHESSYS_BIN = /usr/RHESSys/bin
GISLIB = -lgrass_gis
GISDATE = -lgrass_datetime
CFLAGS = -g
OBJECTS = \
main.o \
log.o

OS := $(shell uname)

$(PGM): $(OBJECTS)
ifeq ($(OS), Darwin)
	$(CC) $(CFLAGS) $(OBJECTS) -L$(GISBASE)/lib -o $(PGM) $(GISLIB) $(GISDATE) $(XDRLIB) -lm
else ifeq ($(OS), Linux)
	$(CC) $(CFLAGS) $(OBJECTS) -L$(GISBASE)/lib -Wl,-rpath=$(GISBASE)/lib -o $(PGM) $(GISLIB) $(GISDATE) $(XDRLIB) -lm
else
	$(CC) $(CFLAGS) $(OBJECTS) -L$(GISBASE)/lib -Wl,-rpath=$(GISBASE)/lib -o $(PGM) $(GISLIB) $(GISDATE) $(XDRLIB) -lm
endif

main.o:
	$(CC) $(CFLAGS) -I$(GISBASE)/include -c main.c -o main.o
log.o:

install:
	cp $(PGM) $(RHESSYS_BIN)

clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(PGM)


I am a beginner of Linux and RHESSys, and hope there are someone can help to solve this problem. Thanks!
