### ISSUE TITLE
Update hydro_routing to reflect actual units if sat_to_gw_coeff

### ISSUE THREAD

**Issue by selimnairb** [RHESSys/RHESSys#49]
@xiaoli-chen says sat_to_gw_coeff is in units of percent/day, not percent/hour

**Comment by selimnairb** [comment]
@cjcoats Has this been resolved?

**Comment by selimnairb** [comment]
Line 1565 should be:

gwcoef[i] = patch->soil_defaults[0][0].sat_to_gw_coeff / (24 * 60 * 60);

Because we need units to be in per second units.

**Comment by cjcoats** [comment]
Brian Miles wrote:
> @xiaoli-chen <https://github.com/xiaoli-chen> says sat_to_gw_coeff is in
> units of percent/day, not percent/hour

Done.

Check that I got the commit-message right, so that it refers to
issue #49.

Note the additional change to gwcoef[] -- hydro_routing assumes that
it should be in 1/Sec units instead of %/Day, so that the conversion
factor is (1.0/(24,0*3600.0*100.0)).


-- Carlie

**Comment by selimnairb** [comment]
@cjcoats I don't see a recent commit from you to the 40-variable-timestep-routing branch.  Did you push?

**Comment by cjcoats** [comment]
Brian Miles wrote:
> @cjcoats <https://github.com/cjcoats> I don't see a recent commit from
> you to the 40-variable-timestep-routing branch. Did you push?


...working on the pull-and-fix.


-- Carlie

**Comment by selimnairb** [comment]
Commit 0ba92103753e5219669f2bb95fa316cdd6df135f addresses this, closing.
