### ISSUE TITLE
Installed RHESSYS Not Compiling 

### ISSUE THREAD

**Issue by koadean** [RHESSys/RHESSys#58]
Aloha, we have installed RHESSYS from the fiesta.bren.ucsb.edu webpage for some research in New Zealand but it is not compiling. I had a systems engineer have a look at it and she says that the underlying code has a number of errors and it won't compile. Is there a bug free version of RHESSYS that we can access? Cheers

**Comment by xiaoli-chen** [comment]
Aloha:)
      I just checked our newest branch and they did compile. I guess you might find a really old version of RHESSys. Did you check the webpage: https://github.com/RHESSys/RHESSys/wiki/How-to-get-RHESSys  ? I think that page is correct.
     Please let us know if you still have problems.

Best,
Xiaoli

**Comment by koadean** [comment]
Thanks for the quick reply. We will install version 5.18.2 and let you know if we are successful. Cheers Dean

**Comment by naomitague** [comment]
Dean

I do recommend that you install the Master version from the githup page
https://github.com/RHESSys/RHESSys

Naomi

On Tue, Sep 22, 2015 at 4:45 AM, koadean <notifications@github.com> wrote:

> Aloha, we have installed RHESSYS from the fiesta.bren.ucsb.edu webpage
> for some research in New Zealand but it is not compiling. I had a systems
> engineer have a look at it and she says that the underlying code has a
> number of errors and it won't compile. Is there a bug free version of
> RHESSYS that we can access? Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/58>.
>



-- 
Tague Ecohydrology Lab
www.ecohydrolab.com

**Comment by koadean** [comment]
Aloha Xiaoli and Naomi,

My intern tried to installed the User version (5.18.2) and hit the same problems with initialisation. We will try the Master version instead. 

Cheers
Dean

**Comment by selimnairb** [comment]
Hi Dean,

Please include the error messages you are receiving.  Without specific error messages, it is not possible for anyone to help you.  Also, what operating system and compiler are you using?

Thanks,

Brian

**Comment by jschoate** [comment]
Hi Dean,
if you are installing on Mac OS X, hopefully these instructions on the wiki will successfully help you install GRASS and RHESSys:
https://github.com/RHESSys/RHESSys/wiki/How-to-get-RHESSys
https://github.com/RHESSys/RHESSys/wiki/Installing-RHESSys-and-associated-programs---Mac-OS-X

Janet

**Comment by koadean** [comment]
Aloha all,

We have tried to install the Master version and we get errors when trying to compile rat. See below. We are installing RHESSYS to a PC with a Linux Mint 17.2 x64 KDE OS. GRASS is installed and running. Cheers Dean

main.c: In function "main":
main.c:99:23: error: storage size of "cats" isn"t known
     struct Categories cats;
                       ^
main.c:251:17: warning: assignment makes pointer from integer without a cast [enabled by default]
    if (!(mapset = G_find_cell(temp_table, "")))
                 ^
main.c:434:5: warning: format "%ld" expects argument of type "long int *", but argument 3 has type "int *" [-Wformat=]
     if (fscanf(fd1, "%ld", &(basecat[basemap])) != 1)
     ^
main.c:448:7: warning: format "%ld" expects argument of type "long int", but argument 4 has type "int" [-Wformat=]
       sprintf (temp_str1, "read basecat[%d] = %ld\n", basemap, basecat[basemap]);
       ^
main.c:483:7: warning: format "%ld" expects argument of type "long int", but argument 3 has type "int" [-Wformat=]
       sprintf (temp_str1, "read covercat = %ld area = %lf\n", covercat, area);
       ^
main.c:538:7: warning: format "%ld" expects argument of type "long int", but argument 3 has type "int" [-Wformat=]
       sprintf (buf, "%ld", sum3);
       ^
main.c:555:8: warning: format "%ld" expects argument of type "long int", but argument 3 has type "int" [-Wformat=]
        fprintf(fd2, "%ld ", oldbasecat[basemap]);
        ^
main.c:558:9: warning: format "%ld" expects argument of type "long int", but argument 3 has type "int" [-Wformat=]
         sprintf (temp_str1, "outputing for first cover map %ld\n", oldbasecat[basemap]);
         ^
main.c:666:4: warning: format "%ld" expects argument of type "long int *", but argument 3 has type "int *" [-Wformat=]
    fscanf(the_file[firstcovermap], "%ld", &basecat[basemap]);
    ^
main.c:669:5: warning: format "%ld" expects argument of type "long int", but argument 4 has type "int" [-Wformat=]
     sprintf(temp_str1, "read basecat[%d] = %ld\n", basemap, basecat[basemap]);
     ^
main.c:726:7: warning: format "%ld" expects argument of type "long int", but argument 3 has type "int" [-Wformat=]
       fprintf(fd3, "%6ld", basecat[j]);        
       ^
main.c:729:8: warning: format "%ld" expects argument of type "long int", but argument 4 has type "int" [-Wformat=]                                                                                                          
        sprintf(temp_str1, "writing basecat[%d] = %6ld\n", j, basecat[j]);                                                                                                                                                  
        ^                                                                                                                                                                                                                   
main.c:735:7: warning: format "%ld" expects argument of type "long int", but argument 3 has type "int" [-Wformat=]                                                                                                          
       fprintf(fd3, " %ld", basecat[j]);                                                                                                                                                                                    
       ^                                                                                                                                                                                                                    
main.c:738:8: warning: format "%ld" expects argument of type "long int", but argument 4 has type "int" [-Wformat=]                                                                                                          
        sprintf(temp_str1, "writing basecat[%d] = %ld\n", j, basecat[j]);                                                                                                                                                   
        ^                                                                                                                                                                                                                   
main.c:746:7: warning: format "%ld" expects argument of type "long int", but argument 3 has type "int" [-Wformat=]                                                                                                          
       fprintf(fd3, "%6ld", (int)(covervalue[j]));                                                                                                                                                                          
       ^                                                                                                                                                                                                                    
main.c:749:8: warning: format "%ld" expects argument of type "long int", but argument 4 has type "int" [-Wformat=]                                                                                                          
        sprintf(temp_str1, "writing covervalue[%d] = %6ld\n", j, (int)covervalue[j]);                                                                                                                                       
        ^                                                                                                                                                                                                                   
main.c:755:7: warning: format "%ld" expects argument of type "long int", but argument 3 has type "int" [-Wformat=]                                                                                                          
       fprintf(fd3, " %ld", (int)(covervalue[j]));                                                                                                                                                                          
       ^
main.c:758:8: warning: format "%ld" expects argument of type "long int", but argument 4 has type "int" [-Wformat=]
        sprintf(temp_str1, "writing covervalue[%d] = %ld\n", j, (int)covervalue[j]);
        ^
make: *** [main.o] Error 1

**Comment by selimnairb** [comment]
@koadean Have you set the GISBASE environment variable?  GISBASE should point to directory that contains your GRASS 6.4x installation (we haven't tested with GRASS 7 yet).

**Comment by jschoate** [comment]
Hi Dean,
hopefully these instructions on the wiki will successfully help you install
GRASS and RHESSys:
https://github.com/RHESSys/RHESSys/wiki/How-to-get-RHESSys
https://github.com/RHESSys/RHESSys/wiki/Installing-RHESSys-and-associated-programs---Mac-OS-X

Janet

On Wed, Sep 23, 2015 at 6:59 PM, Brian Miles <notifications@github.com>
wrote:

> @koadean <https://github.com/koadean> Have you set the GISBASE
> environment variable? GISBASE should point to directory that contains your
> GRASS 6.4x installation (we haven't tested with GRASS 7 yet).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/58#issuecomment-142781869>.
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by jschoate** [comment]
there are problems with g2w/rat with GRASS 7.
please use GRASS 6.4 until this is resolved.
Janet

On Wed, Sep 23, 2015 at 9:40 PM, Janet Choate <jsc.eco@gmail.com> wrote:

> Hi Dean,
> hopefully these instructions on the wiki will successfully help you
> install GRASS and RHESSys:
> https://github.com/RHESSys/RHESSys/wiki/How-to-get-RHESSys
>
> https://github.com/RHESSys/RHESSys/wiki/Installing-RHESSys-and-associated-programs---Mac-OS-X
>
> Janet
>
> On Wed, Sep 23, 2015 at 6:59 PM, Brian Miles <notifications@github.com>
> wrote:
>
>> @koadean <https://github.com/koadean> Have you set the GISBASE
>> environment variable? GISBASE should point to directory that contains your
>> GRASS 6.4x installation (we haven't tested with GRASS 7 yet).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RHESSys/RHESSys/issues/58#issuecomment-142781869>.
>>
>
>
>
> --
> Tague Team Lab Manager
> 1005 Bren Hall
> UCSB, Santa Barbara, CA.
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by jschoate** [comment]
you may also want to review this wiki page on installing RHESSys programs
on linux:
https://github.com/RHESSys/RHESSys/wiki/Installing-RHESSys-programs-on-Linux
Janet

On Wed, Sep 23, 2015 at 9:41 PM, Janet Choate <jsc.eco@gmail.com> wrote:

> there are problems with g2w/rat with GRASS 7.
> please use GRASS 6.4 until this is resolved.
> Janet
>
> On Wed, Sep 23, 2015 at 9:40 PM, Janet Choate <jsc.eco@gmail.com> wrote:
>
>> Hi Dean,
>> hopefully these instructions on the wiki will successfully help you
>> install GRASS and RHESSys:
>> https://github.com/RHESSys/RHESSys/wiki/How-to-get-RHESSys
>>
>> https://github.com/RHESSys/RHESSys/wiki/Installing-RHESSys-and-associated-programs---Mac-OS-X
>>
>> Janet
>>
>> On Wed, Sep 23, 2015 at 6:59 PM, Brian Miles <notifications@github.com>
>> wrote:
>>
>>> @koadean <https://github.com/koadean> Have you set the GISBASE
>>> environment variable? GISBASE should point to directory that contains your
>>> GRASS 6.4x installation (we haven't tested with GRASS 7 yet).
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/RHESSys/RHESSys/issues/58#issuecomment-142781869>.
>>>
>>
>>
>>
>> --
>> Tague Team Lab Manager
>> 1005 Bren Hall
>> UCSB, Santa Barbara, CA.
>>
>
>
>
> --
> Tague Team Lab Manager
> 1005 Bren Hall
> UCSB, Santa Barbara, CA.
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by koadean** [comment]
Aloha everyone,
We had GRASS 7 installed. It was uninstalled, after some effort we installed GRASS 6.4 (LINUX was assisting of installing v7), and we don't have the above errors anymore. We still have to go through the rest of the installation process but it is looking promising, I will close this issue when(if) RHESSys is  successfully installed. Thanks all for your help. Cheers Dean

**Comment by koadean** [comment]
Aloha again, we have RHESSYS up and running. Still have to test it with a dataset but it appears to be running. Thanks again. Cheers Dean

**Comment by jds485** [comment]
Is using GRASS 7 still an issue? I'm currently having problems installing rat, and am wondering if using GRASS 7 is a problem.

**Comment by jschoate** [comment]
no problem using GRASS 7 now - 
however - you no longer need to use the GRASS/RHESSys interface programs g2w/rat & cf.
we can now generate the worldfile and flowtable in R - in fact this is preferable - and if you want to use the develop version of RHESSys (rhessys7.0) then you must generate worldfile/flowtable with the new RHESSysPreprocessing R package. Please see documentation here:
https://github.com/RHESSys/RHESSys/wiki/RHESSys6.0-new-functionalityhttps://github.com/RHESSys/RHESSys/wiki/Worldfile#rhessys-preprocessing-in-r
