### ISSUE TITLE
RHESSys5.19 output producing sat_def, baseflow, streamflow as "nan" 

### ISSUE THREAD

**Issue by arnabbandyo** [RHESSys/RHESSys#64]
Hi,

I am trying to run RHESSys5.19 for an eastern Himalayan watershed. Everything seems to be working perfectly without any error. However, when I open the output file out_basin.daily, I find sat_def (although sat_def_z has values), baseflow, and streamflow has recorded "nan" (not a number) only.

Can you give me some hint, what I am doing wrong or where should I look for the cause of this problem?

Regards.

Arnab

**Comment by xiaoli-chen** [comment]
Arnab,
Interesting. What's the size of your research area?

Xiaoli

**Comment by arnabbandyo** [comment]
Dear Xiaoli,

The basin area is 52 sq. km. DEM resolution is 29 m.

Arnab

**Comment by arnabbandyo** [comment]
Any ideas, Xiaoli?

What should I try different to get rid of this problem? I can share my input files (defs, worldfiles, etc.) if you want to check.

Regards.

Arnab

**Comment by xiaoli-chen** [comment]
could you share the whole project with me via google drive ?



Xiaoli

**Comment by arnabbandyo** [comment]
Here you go:
https://drive.google.com/folderview?id=0B6wW_TPW4czpQU9ydUJjOFhlejQ&usp=sharing

Please let me know what is wrong with this!

**Comment by arnabbandyo** [comment]
Dear Xiaoli,

Please ignore the earlier link as it points to a folder which you cannot download at one go.

Here is the link to the complete project zipped into a single file which will be easier and much smaller to download for you:

https://drive.google.com/file/d/0B6wW_TPW4czpbHlwak5kN1RISDg/view?usp=sharing

Please let me know if you face any problem in downloading/ unzipping it.

Regards.

Arnab

**Comment by jschoate** [comment]
Arnab,
i had a look at your files - and while i haven't found exactly what is
wrong here - i did find a few other problems.

in your tecfile, you can not have two events that occur simultaneously. if
you want two events to occur on the same day, then you must start them at
different hours, i.e.
2009 4 6 1 print_daily_on
2009 4 6 2 print_montly_on

your input climate files - are you sure your rain input is in meters?

the values for your east and west horizons seem off.
please create your maps using the following directions in the wiki:
https://github.com/RHESSys/RHESSys/wiki/East-and-West-Horizon-Maps

did you create the flowtable with cf10.0b3?

Janet

On Wed, Oct 14, 2015 at 12:40 AM, arnabbandyo <notifications@github.com>
wrote:

> Dear Xiaoli,
>
> Please ignore the earlier link as it points to a folder which you cannot
> download at one go.
>
> Here is the link to the complete project zipped into a single file which
> will be easier and much smaller to download for you:
>
>
> https://drive.google.com/file/d/0B6wW_TPW4czpbHlwak5kN1RISDg/view?usp=sharing
>
> Please let me know if you face any problem in downloading/ unzipping it.
>
> Regards.
>
> Arnab
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/64#issuecomment-147963849>.
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by arnabbandyo** [comment]
Janet,

Thanks.

Yes, the flowtable was created with cf10.0b3 and the rain input is in meters. The other two things I will correct and report.

Arnab

**Comment by arnabbandyo** [comment]
Janet, 

My student just informed me that in the particular example that I have sent you, precipitation is in mm. We corrected it long back but unfortunately sent you an older project folder. However, that is not causing the "nan".

In case of east and west horizons, there is mismatch in the name of the state variables. Actually we don't have a proper worldfile template for the current version of RHESSys and modified one from version 5.14.7. That might be causing other problems as well. Can you send one proper worldfile template?

Regards.

Arnab

**Comment by arnabbandyo** [comment]
Hi Janet and Xiaoli,

Here is the updated project folder:
https://drive.google.com/file/d/0B6wW_TPW4czpN3BBMHA3SkZIZGM/view?usp=sharing

The following changes were made:
1. The tecfile is edited as suggested
2. In climate file, rain input given in meters.
3. East and West horizons are corrected as suggested.

But the output is still giving "nan" in sat_def, baseflow, and streamflow.

Please help me in sorting this out. I would also appreciate if you can send me a correct template for creating worldfile for RHESSys5.19.

Regards.

Arnab

**Comment by jschoate** [comment]
Hi Arnab,
attached is a compatible template for rhessys5.19. you will of course need
to edit it with your correct def files, maps, latitude, values.

also, your definition files (i.e. veg_grass1.def, etc...) have not been
updated for compatibility with rhessys5.19.
please read the attached Change_defs.pdf document and use the
Correct_defs.tar utilities to correct your def files.
essentially - this corrects misspelled parameter names as RHESSys now reads
in parameters by exact name rather than by order in which the parameter is
listed. if you have a missing or misspelled parameter name - then RHESSys
will use the default value in the code, which is a conifer for veg type and
sandy loam for soil type.
also, i notice that there is no difference between your 3 grass files other
than the default_ID - so all 3 files will act exactly the same - behavior
will not be different between them, and the same goes for your 3 shrub
files and your 4 soil files.

and - in 5.19, there were changes made in the calculation of atmospheric
transmissivity (which may impact transpiration). There are 2 parameters
that affect the calculation of atmospheric transmissivity now if they are
included in the zone definition file (most of you do have these in your
zone def files as up until now this has been standard).

So that these parameters do not provide a coefficient that affects the
calculation of atmospheric transmissivity, please delete them from your
zone definition files so the code will by default calculate the coefficient
as a function of deltaT.

RHESSys 5.19 users please delete:

trans_coeff1 and trans_coeff2

from you zone def files.

i will add you to the RHESSys user list so you will receive future emails
about updates.

Janet

On Thu, Oct 15, 2015 at 5:07 AM, arnabbandyo <notifications@github.com>
wrote:

> Hi Janet and Xiaoli,
>
> Here is the updated project folder:
>
> https://drive.google.com/file/d/0B6wW_TPW4czpN3BBMHA3SkZIZGM/view?usp=sharing
>
> The following changes were made:
> 1. The tecfile is edited as suggested
> 2. In climate file, rain input given in meters.
> 3. East and West horizons are corrected as suggested.
>
> But the output is still giving "nan" in sat_def, baseflow, and streamflow.
>
> Please help me in sorting this out. I would also appreciate if you can
> send me a correct template for creating worldfile for RHESSys5.19.
>
> Regards.
>
> Arnab
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/64#issuecomment-148367456>.
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by arnabbandyo** [comment]
Janet,

How do I get those files? The compatible template, Change_defs.pdf, Correct_defs.tar? I think all file types cannot be attached in Github comments. Can you Please email them to arnabbandyo@gmail.com?

Regarding the same properties in all soil, grass, and shrub files, this is our very first run and we will update the values once we successfully run the model. I do understand that they are all now behaving exactly same.

Regards.

Arnab

**Comment by jschoate** [comment]
Arnab,
I just sent the files to your gmail email account.

understood on the def files - just wanted to make sure it wasn't an
overlooked error.
Janet

On Thu, Oct 15, 2015 at 6:39 PM, arnabbandyo <notifications@github.com>
wrote:

> Janet,
>
> How do I get those files? The compatible template, Change_defs.pdf,
> Correct_defs.tar? I think all file types cannot be attached in Github
> comments. Can you Please email them to arnabbandyo@gmail.com?
>
> Regarding the same properties in all soil, grass, and shrub files, this is
> our very first run and we will update the values once we successfully run
> the model. I do understand that they are all now behaving exactly same.
>
> Regards.
>
> Arnab
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/64#issuecomment-148571574>.
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by arnabbandyo** [comment]
Janet,

With the help of the materials sent by you, I have been able to correct my def files and create a new worldfile with the compatible template.

Here is the updated project folder:
https://drive.google.com/file/d/0B6wW_TPW4czpa0Fra0Q1V2UxZEE/view?usp=sharing

However, the basic problems remain the same. It is still recording "nan" in the output.

What do you want me to try next?

Arnab

**Comment by arnabbandyo** [comment]
I am beginning to think that this might be a hardware issue! I am using a MacBookPro now. Shall I try to compile and run RHESSys5.19 on a Linux system?

**Comment by jschoate** [comment]
Arnab,
actually, Mac is the preferred system.
process of elimination - my recommendation is that you re-download the most
current version of RHESSys, following the wiki instructions:
https://github.com/RHESSys/RHESSys/wiki/How-to-get-RHESSys

IMPORTANT: if you are just overwriting the existing directory - before you
try to recompile the newly downloaded version, make sure that you do not
have any file in the rhessys/objects directory. when you download the
rhessys files, you have several directories: g2w, cf, rhessys, util. when
you compile rhessys it creates an objects sub-directory within the rhessys
directory. either delete the objects directory or delete all the files in
it.

then recompile rhessys, following the instructions for "Local installation
of RHESSys" found on the wiki here:
https://github.com/RHESSys/RHESSys/wiki/Installing-RHESSys-and-associated-programs---Mac-OS-X

then test your run with this newly compiled version of rhessys.
Janet

On Sat, Oct 17, 2015 at 8:49 AM, arnabbandyo <notifications@github.com>
wrote:

> I am beginning to think that this might be a hardware issue! I am using a
> MacBookPro now. Shall I try to compile and run RHESSys5.19 on a Linux
> system?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/64#issuecomment-148926015>.
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by arnabbandyo** [comment]
Janet,
While I do as you have suggested above, may I request you to run our project in your system once and share the output file please? Then it will be clear if model/ system is causing the "nan" or the problem is in our data/ setup. The script is written in script.2009 in the scripts folder.
Regards.
Arnab

**Comment by arnabbandyo** [comment]
Downloaded and compiled (local install) RHESSys afresh as suggested by you. Nothing changed. Still getting "nan" as earlier. What next? I am out of ideas now... :(

**Comment by xiaoli-chen** [comment]
Hi Arnabbandyo,
     When I ran your project, I stopped the program during running time and
checked value. The streamflow variables did have values. However, there are
a few patches always producing 'nan' value. When rhessys sum up the value
for the whole watershed, it is these several patches which messed up the
whole output.

     I'll try it later today and tell you the patch IDs for these 'bugs'.

Best,
Xiaoli

On Wed, Oct 21, 2015 at 10:40 AM, arnabbandyo <notifications@github.com>
wrote:

> Downloaded and compiled (local install) RHESSys afresh as suggested by
> you. Nothing changed. Still getting "nan" as earlier. What next? I am out
> of ideas now... :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/64#issuecomment-149973329>.
>



-- 
Xiaoli Chen

Bren School of Environmental Science and Management
University of California, Santa Barbara
xiaoli_chen@umail.ucsb.edu

**Comment by jschoate** [comment]
Arnab,
thank you to Xiaoli for troubleshooting this and finding the 'missing'
patches.
Arnab - when you created the various maps in grass, did you have a MASK on
when you created any of them? in particular - the patch map?
if you created maps with the MASK on, then the problem could be an 'edge'
effect - where there are slight differences, missing values, around the
edges of one or more of the maps - where they do not all completely align.
if this is the case - please remake your maps for the full extent of your
project/DEM (or at least an extent a bit larger than your watershed
boundary) - without the watershed basin MASK on.
then remake your worldfile/flowtable with the new map(s), rerun simulation.
Janet

On Wed, Oct 21, 2015 at 10:47 AM, Xiaoli Chen <notifications@github.com>
wrote:

> Hi Arnabbandyo,
> When I ran your project, I stopped the program during running time and
> checked value. The streamflow variables did have values. However, there are
> a few patches always producing 'nan' value. When rhessys sum up the value
> for the whole watershed, it is these several patches which messed up the
> whole output.
>
> I'll try it later today and tell you the patch IDs for these 'bugs'.
>
> Best,
> Xiaoli
>
> On Wed, Oct 21, 2015 at 10:40 AM, arnabbandyo <notifications@github.com>
> wrote:
>
> > Downloaded and compiled (local install) RHESSys afresh as suggested by
> > you. Nothing changed. Still getting "nan" as earlier. What next? I am out
> > of ideas now... :(
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/RHESSys/RHESSys/issues/64#issuecomment-149973329>.
> >
>
>
>
> --
> Xiaoli Chen
>
> Bren School of Environmental Science and Management
> University of California, Santa Barbara
> xiaoli_chen@umail.ucsb.edu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/64#issuecomment-149974985>.
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by arnabbandyo** [comment]
Thank you Xiaoli and Janet.

I shall recreate the maps without the MASK as suggested and update you.

Regards.

Arnab

**Comment by arnabbandyo** [comment]
Xiaoli and Janet,
A BIG BIG THANK YOU to both of you. Finally I have got NUMBERS and not "NaN" in my streamflow series. Yes, it was caused by edge effect generated due to MASKing the raster layers.
Arnab

**Comment by xiaoli-chen** [comment]
Awesome!!! High five!

**Comment by selimnairb** [comment]
@arnabbandyo You can build your worldfiles using [RHESSysWorkflows](https://github.com/selimnairb/RHESSysWorkflows), which will avoid error-prone steps like having to remember to turn raster masking off in GRASS.
