### ISSUE TITLE
compute_potential_exfiltration always returns 0 as currently called

### ISSUE THREAD

**Issue by selimnairb** [RHESSys/RHESSys#67]
As compute_potential_exfiltration() is called right now in patch_daily_I.c (e.g. [here](https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/patch_daily_I.c#L352)), the argument named "p" is porosity_0, while the porosity_decay is being passed in as "p_0". Thus, the updated equation appears to be wrong. The correct fix would appear to be to change the function definition such that the final argument is named "p_0", and the penultimate argument should be named "p".

Will also add a unit test for this while fixing.

**Comment by xiaoli-chen** [comment]
Brian,
    I see what you mean. 
    When we found the bug in the file 'compute_potential_exfiltration.c', the definition of the last two input variables are:
/*	double 	p_0  (dim) - porosity  at surface 		*/
/*	double 	p  (m-1) - porosity  decay rate 	       */
   
     Later in line 94 when calculating the mean porosity, the previous version was using:
	porosity_average = p * p_0 * (1-exp(-1*sat_deficit_z/p_0)) / sat_deficit_z;

     Which, should be, 
	porosity_average = p * p_0 * (1-exp(-1*sat_deficit_z/p)) / sat_deficit_z;

     We made change to fix the bug here. 
     However, we didn't notice that in file 'cycle/patch_daily_I.c' where the function 'compute_potential_exfiltration' is called in line 352, the order of input variables is wrong too.
     Now it is:
				patch[0].potential_exfiltration = compute_potential_exfiltration(
                                              ......
					patch[0].soil_defaults[0][0].porosity_decay,
					patch[0].soil_defaults[0][0].porosity_0);

        Where it should be:
				patch[0].potential_exfiltration = compute_potential_exfiltration(
                                               ......
					patch[0].soil_defaults[0][0].porosity_0,
					patch[0].soil_defaults[0][0].porosity_decay);

         You are right, to exchange the order of p_0 and p in the function definition in file compute_potential_exfiltration.c is easier.
         
         Have you already made the correction? I can do it if you haven't done that.
         Sorry for the confusion.

**Comment by selimnairb** [comment]
@xiaoli-chen I've already made the change in two branches: 67-master-fix-poten-exfil and 67-fix-poten-exfil (the former being applied over top master).  We'll do some testing, and I'll be adding a unit test for compute_potential_exfiltration().  Once these are done, we should do a bug fix release on master and also merge the changes back into develop.  Hopefully sometime next week.
