### ISSUE TITLE
Canopy, litter, detention store, and soil evaporation are limited to daytime hours

### ISSUE THREAD

**Issue by selimnairb** [RHESSys/RHESSys#70]
In surface_daily_F(), canopy, litter, detention store, and soil evaporation are limited to daytime hours.  For [example](https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/surface_daily_F.c#L279):

    detention_store_potential_evaporation  = detention_store_potential_dry_evaporation_rate
					* (zone[0].metv.dayl - (zone[0].daytime_rain_duration * zone[0].metv.dayl/86400) )
					+ detention_store_potential_rainy_evaporation_rate
					* (zone[0].daytime_rain_duration * zone[0].metv.dayl/86400);

where "(zone[0].metv.dayl - (zone[0].daytime_rain_duration * zone[0].metv.dayl/86400) )" equals the number of daytime hours without rain, and "(zone[0].daytime_rain_duration * zone[0].metv.dayl/86400)" equals the number of daytime hours with rain.

Additionally, the average net radiation calculation appears to be an average over daylight hours, as per [here](https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/surface_daily_F.c#L242):

    if (zone[0].metv.dayl > ZERO) {
				rnet_evap_pond = 1000 * ( (1-WATER_ALBEDO) * (patch[0].Kdown_direct + patch[0].Kdown_diffuse) 
										+ patch[0].Lstar_pond
										/* - patch[0].Lstar_soil */ /* Lstar_soil is assumed 0 when ponded water */
										+ patch[0].surface_heat_flux ) 
										/ zone[0].metv.dayl;

Given that evaporation does occur in the absence of PAR (though often at a lower rate), it seems that net long wave radiation and surface_heat_flux need to be partitioned between daytime and nighttime hours.  Then, net radiation for daytime and nighttime hours need to be calculated, something like:

    rnet_evap_pond_day = 1000 * ( (1-WATER_ALBEDO) * (patch[0].Kdown_direct + patch[0].Kdown_diffuse) 
										+ patch[0].Lstar_pond_day
										/* - patch[0].Lstar_soil */ /* Lstar_soil is assumed 0 when ponded water */
										+ patch[0].surface_heat_flux_day ) 
										/ zone[0].metv.dayl;

    rnet_evap_pond_night = 1000 * ( patch[0].Lstar_pond_night
										/* - patch[0].Lstar_soil */ /* Lstar_soil is assumed 0 when ponded water */
										+ patch[0].surface_heat_flux_night ) 
										/ (86400 - zone[0].metv.dayl);

Given net radiation for day and night, we can calculate potential evaporation (rainy and dry) for the day as well as the night, which can be multiplied by rain duration, and then summed together to calculate total daytime and nighttime evaporation fluxes.  Something like:

    day_rain_duration = zone[0].daytime_rain_duration * zone[0].metv.dayl/86400
    detention_store_potential_evaporation_day  = detention_store_potential_dry_evaporation_rate_day
					* (zone[0].metv.dayl - day_rain_duration)
					+ detention_store_potential_rainy_evaporation_rate_day
					* day_rain_duration;

    night_rain_duration = zone[0].daytime_rain_duration - day_rain_duration
    detention_store_potential_evaporation_night  = detention_store_potential_dry_evaporation_rate_night
					* (zone[0].metv.dayl - night_rain_duration )
					+ detention_store_potential_rainy_evaporation_rate_night
					* night_rain_duration;
    detention_store_potential_evaporation = detention_store_potential_evaporation_day + detention_store_potential_evaporation_night

**Comment by selimnairb** [comment]
@naomitague @aubreyd Could you look this over to make sure that I am not missing something?  Thanks.

**Comment by naomitague** [comment]
Brian

Interestingly I just saw all of these messages (I had somehow targeted
Git messages to a folder that I rarely read...guess I should change this)
What you say makes sense - but would be useful to hear from Aubrey as well
as I know she made changes to daylight part of the code

I will caution you that longwave radiation estimates are often poor - and
can be a bit source of error! - Not really due to a bug - but because
equation is highly non-linear with air temperature - so feedbacks and
micro-climates can really matter
We occasionally simply have to turn off the longwave contributions to
things as that yields less error than including it (and since long wave
more or less is correlated with PAR this works as an approximation)

N

On Tue, Dec 15, 2015 at 11:31 PM, Brian Miles <notifications@github.com>
wrote:

> @naomitague <https://github.com/naomitague> @aubreyd
> <https://github.com/aubreyd> Could you look this over to make sure that I
> am not missing something? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/70#issuecomment-164903684>.
>



-- 
Tague Ecohydrology Lab
www.ecohydrolab.com

**Comment by selimnairb** [comment]
@aubreyd When you have a chance, could you look through the above proposed code and see if you think it looks reasonable.  One thing I did not include was how to partition net long wave radiation between day and night.  I looks like at least part of this is done in commented out code [here](https://github.com/RHESSys/RHESSys/blob/master/rhessys/rad/compute_Lstar.c#L94):

```
/* With day/night split (not highly sensitive) */
patch[0].Lup_canopy_night = ess_veg * SBC * pow( zone[0].metv.tnight + 273.0, 4.0 ) * nightlength / 1000.0;
patch[0].Lup_canopy_day = ess_veg * SBC * pow( zone[0].metv.tday +	273.0, 4.0 ) * daylength / 1000.0;
patch[0].Lup_canopy =   patch[0].Lup_canopy_day  + patch[0].Lup_canopy_night + (1 - ess_veg) * zone[0].Ldown;
Ldown_canopy = patch[0].Lup_canopy_day  + patch[0].Lup_canopy_night;
```

I think the only thing I see missing here is partitioning Lup_snow, Lup_pond, and Lup_soil into day and night portions, which for a first approximation, I will partition based on hours of daylight per day (though do let me know if this is not correct).

No need to answer all of these questions up front in the issue.  We will have a chance to review and comment once I issue the pull request.
