### ISSUE TITLE
Wordfile creation problems #1

### ISSUE THREAD

**Issue by koadean** [RHESSys/RHESSys#71]
Hi, we are having problems with the creation of our wordfile. We get the error message "error reading template file". Could you help in the following:
1) Is there a way to get g2W to display where it is reading the error?
2) Is this error due to a file reading issue or an error with the template?

**Comment by koadean** [comment]
We made a little more progress but we get either the error message "expecting '_' ", or "segmentation fault". Any help would be appreciated. Here is the file we have assembled: 

$num_basin_defs
$basin_defs
$num_hillslope_defs
$hillslope_defs
$num_zone_defs
$zone_defs
$num_soil_defs
$soil_defs
$num_landuse_defs
$landuse_defs
$num_stratum_defs
$stratum_defs
$num_climate_stations
$climate_stations
_world $Puruki 1
 _basin $Puruki 1
	x			aver $xcoords
	y			aver $ycoords
	z			eqn 0.001 0.0 $purdem
	basin_parm_ID	dvalue 1
	latitude		value -38.429
	n_basestations 	dvalue 0	
  	_hillslope $purhillslope 1
		x			aver $xcoords
		y			aver $ycoords
		z			eqn 0.001 0.0 $purdem
		hill_parm_ID		dvalue 1
		gw.storage		value 0.0
		gw.NO3			value 0.0
		n_basestations	dvalue 0 	
		_zone $purhillslope 1 
			x			aver $xcoords
			y			aver $ycoords
			z			eqn 0.001 0.0 $purdem
			zone_parm_ID		dvalue 1
			area		area	
			slope		aver $slope.p
			aspect		spavg $aspect.p $aspect.p slope.p
			precip_lapse_rate	value 1.0 
			e_horizon    eqn 0.001 0.0  $east.p	
			w_horizon    eqn 0.001 0.0  $west.p	
			n_basestations	dvalue $zone_num_base_stations	
			$zone_base_station_ids
			 _patch $purpatch 1
				x			aver $xcoords
				y			aver $ycoords
				z			eqn 0.001 0.0 $purdem
				soil_parm_ID		value 3.0 
				landuse_parm_ID		value 1.0
				area		area	
				slope	aver $slope.p
				lna	value 1.0 
				Ksat_vertical	value 1.0
				mpar			value 0.12 
				rz_storage	value 0.0
				unsat_storage	value	0.0
				sat_deficit 	value	0.0
				snowpack.water_equivalent_depth value 0.28 
				snowpack.water_depth	value 0.0
				snowpack.T 		value -10.0
				snowpack.surface_age	value 0.0
				snowpack.energy_deficit value -0.5 
				litter.cover_fraction	value 1.0
				litter.rain_stored	value 0.0
				litter_cs.litr1c 	value	0.0
				litter_ns.litr1n 	value	0.0
				litter_cs.litr2c 	value	0.0
				litter_cs.litr3c 	value	0.0
				litter_cs.litr4c 	value	0.0
				soil_cs.soil1c 	value	0.0
				soil_ns.sminn	value	0.0
				soil_ns.nitrate	value 0.0
				soil_cs.soil2c	value	0.0	
				soil_cs.soil3c   	value	0.0
				soil_cs.soil4c	value	0.0
				n_basestations	dvalue 0
				_stratum $purpatch 1	
					veg_parm_ID		value 1.0
					cover_fraction	value 1.0
					gap_fraction	value 0.5
					rootzone.depth		value 1.0
					snow_stored		value 0.0 
					rain_stored		value 0.0  
					cs.cpool			value 0.0
					cs.leafc		value 0.0
					cs.dead_leafc		value 0.0 
					cs.leafc_store		value 0.0
					cs.leafc_transfer	value 0.0 
					cs.live_stemc		value 0.0
					cs.live_stemc_store	value 0.0
					cs.live_stemc_transfer	value 0.0 
					cs.dead_stem		value 0.0
					cs.dead_stemc_store	value 0.0
					cs.dead_stemc_transfer	value 0.0  
					cs.live_crootc		value 0.0
					cs.live_crootc_store	value 0.0
					cs.live_crootc_transfer	value 0.0
					cs.dead_crootc		value 0.0
					cs.dead_crootc_store	value 0.0
					cs.dead_crootc_transfer	value 0.0
					cs.frootc		value 0.0
					cs.frootc_store		value 0.0
					cs.frootc_transfer	value 0.0
					cs.cwdc			value 0.0
					epv.prev_leafcalloc	value 0.0
					ns.npool			value 0.0 
					ns.leafn		value 0.0
					ns.dead_leafn		value 0.0
					ns.leafn_store		value 0.0
					ns.leafn_transfer	value 0.0
					ns.live_stemn		value 0.0
					ns.live_stemn_store	value 0.0
					ns.live_stemn_transfer	value 0.0
					ns.dead_stem		value 0.0
					ns.dead_stemn_store	value 0.0
					ns.dead_stemn_transfer	value 0.0
					ns.live_crootn		value 0.0
					ns.live_crootn_store	value 0.0
					ns.live_crootn_transfer	value 0.0  
					ns.dead_crootn		value 0.0
					ns.dead_crootn_store	value 0.0
					ns.dead_crootn_transfer	value 0.0
					ns.frootn		value 0.0
					ns.frootn_store		value 0.0 
					ns.frootn_transfer	value 0.0
					ns.cwdn			value 0.0
					ns.retransn		value 0.0
					epv.wstress_days	dvalue 0 
					epv.max_fparabs		value 0.0 
					epv.min_vwc		value 0.0
					n_basestations 		dvalue 0

**Comment by selimnairb** [comment]
@koadean This looks like a template.template, which RHESSysWorkflows uses to make it worldfile template, but not the worldfile template itself.  Are you using RHESSysWorkflows?

**Comment by koadean** [comment]
Aloha selimnairb, no we are using REHSSYS 5.19 without RHESSYS Workflow. We have assembled the spatial data for creating the worldfile template, but the instructions are unclear on creating the worldfile. Does RHESSYS workflows a better method to assemble the files for creating the worldfile? Cheers

**Comment by jschoate** [comment]
koadean,
i'm not exactly sure on the problem. 
you can set up your rhessys input files either by using RHESSysWorkflows, or setting it up manually. if you are setting up manually - you'll edit the template to read in the appropriate GRASS raster files, then create the worldfile from within GRASS by running the command, for example (at the GRASS terminal window prompt):
g2w -t template.pur -w world.pur

also, i'm not sure why you are using an equation on your dem? i.e.
z eqn 0.001 0.0 $purdem
do you want to multiply your dem by 0.001? 

i've attached a current template here. (let me know if there is any issue accessing it). you'll just need to edit it to use your correct definition, climate, and raster map names.
[template.raw.txt](https://github.com/RHESSys/RHESSys/files/77902/template.raw.txt)
then run g2w with this template from within the GRASS terminal window.

let me know if you still have problems or have success. (sorry for the delay - holidays!)

**Comment by koadean** [comment]
Aloha all, and Happy New Year! @jschoate the manual approach with your .txt file helped, we were able to move further in the worldfile creation process before getting a new error message - but it ran this time:) Please let us know what the error could be:

GRASS 6.4.6svn (NZTM):~/Puruki/RHESSys/bin > g2w -t template.pur -w world.pur


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4593.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4593.0 > tmp
 Executing command rat -z table=BPuruki_ws,XPuruki_ws file=tmpg2m0

 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4603.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4603.0 > tmp
 Executing command rat -z table=bPuruki_ws,BPuruki_ws,Xpur_hillslope file=tmpg2m1

 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4616.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4616.0 > tmp
 Executing command rat -z table=bPuruki_ws,bPuruki_ws,Bpur_hillslope,Xpur_hillslope file=tmpg2m2

 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,patchmap.h10000.alt2 fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4628.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4628.0 > tmp
 Executing command rat -z table=bPuruki_ws,bPuruki_ws,bpur_hillslope,Bpur_hillslope,Xpatchmap.h10000.alt2 file=tmpg2m3

 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,patchmap.h10000.alt2,patchmap.h10000.alt2 fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4641.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4641.0 > tmp
 Executing command rat -z table=bPuruki_ws,bPuruki_ws,bpur_hillslope,bpur_hillslope,Bpatchmap.h10000.alt2,Xpatchmap.h10000.alt2 file=tmpg2m4

 Determining r.stats command in rat
executing command - r.stats -i input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,patchmap.h10000.alt2,patchmap.h10000.alt2, fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4654.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4654.0 > tmp
 Executing command rat -z table=bPuruki_ws,bPuruki_ws,bpur_hillslope,bpur_hillslope,bpatchmap.h10000.alt2,Bpatchmap.h10000.alt2,T0 file=tmpg2m5


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_dem fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4667.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4667.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,BPuruki_ws,Vpur_dem file=tmpg2m1z


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_dem fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4682.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4682.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,Bpur_hillslope,Vpur_dem file=tmpg2m2z


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,pur_dem fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4695.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4695.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,bpur_hillslope,Bpur_hillslope,Vpur_dem file=tmpg2m3z


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope, fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4709.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4709.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,bpur_hillslope,Bpur_hillslope,A file=tmpg2m3area


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,slope.p fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4722.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4722.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,bpur_hillslope,Bpur_hillslope,Vslope.p file=tmpg2m3slope
Removing raster <cos>
Removing raster <sin>
 100%
 100%

 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,sin fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4746.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4746.0 > tmp

 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,cos fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4754.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4754.0 > tmp
 spherical average processing


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,east.p fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4769.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4769.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,bpur_hillslope,Bpur_hillslope,Veast.p file=tmpg2m3e_horizon


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,west.p fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4782.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4782.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,bpur_hillslope,Bpur_hillslope,Vwest.p file=tmpg2m3w_horizon


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,patchmap.h10000.alt2,pur_dem fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4795.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4795.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,bpur_hillslope,bpur_hillslope,Bpatchmap.h10000.alt2,Vpur_dem file=tmpg2m4z


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,patchmap.h10000.alt2, fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4808.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4808.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,bpur_hillslope,bpur_hillslope,Bpatchmap.h10000.alt2,A file=tmpg2m4area


 Determining r.stats command in rat
executing command - r.stats -i -a input=Puruki_ws,Puruki_ws,pur_hillslope,pur_hillslope,patchmap.h10000.alt2,slope.p fs=space output=/home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4821.0
 100%

executing command - sed 's/*/0/g' <  /home/watershed/Puruki/grassdata/NZTM/Ella/.tmp/watershed-desktop/4821.0 > tmp
Processing command rat  -z -k table=bPuruki_ws,bPuruki_ws,bpur_hillslope,bpur_hillslope,Bpatchmap.h10000.alt2,Vslope.p file=tmpg2m4slope
 Opening worldfile world.pur

 ERROR spatial unit ID within world has a value of 0; this is should be fixed as it may invalidate worldfile results

**Comment by jschoate** [comment]
koadean,
this generally results from incomplete raster map alignment. if you made any of your maps while the MASK was on, then you may have an 'edge' effect - where one of the maps doesn't completely line up - it could be just one small tiny sliver of a patch around the edge. 
in GRASS, take off your MASK, then display each of the maps you are using in the worldfile. do they all cover a larger extent than your basin? (other than the basin map obviously!) if any of the maps cover just the basin area, i suggest you remake those with the MASK off so they cover a larger extent than your watershed area. then put the MASK back on and re-run g2w, and see if that fixes the problem in worldfile creation.
again, just want to bring the dem to your attention - is it your intention to multiply it by 0.001? just to make sure, you want your dem to be in meters.

**Comment by koadean** [comment]
jschoate, great, thanks for that tip about the 'edge' effect. Will check today. No, we have no intention for multiplying by 0.001. We have not done that in the new template file. Our DEM is in metres, Our watershed is in New Zealand so creating the files manually works for us.

**Comment by koadean** [comment]
Aloha jschoate, the worldfile is now created. We had a couple of issues with our raster files - our basin file had a value of 0 and the hillslope raster had some cells sticking beyond the basin boundary. Thanks a bunch for pointing us in the right direction! Cheers
