### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/libintl.8.dylib

### ISSUE THREAD

**Issue by rahul1525** [RHESSys/RHESSys#91]
I have been trying to run generation of flowtables for rhessys with the following command in the terminal-

cf10.0b3 output=RHESSys/workspace/grass/flowtables/flowtable.dem template=RHESSys/workspace/grass/worldfiles/templates/template.txt stream=str100 road=zero dem=dem slope=slope cellsize=30.00000000

But it resulted-

dyld: Library not loaded: /usr/local/lib/libintl.8.dylib
  Referenced from: /Applications/GRASS-6.4.app/Contents/MacOS/lib/libgrass_gis.6.4.6svn.dylib
  Reason: image not found
Trace/BPT trap: 5

Trying to find a solution I did installed macports and even run 
sudo ln -s /Applications/Grass/GRASS-6.4.app/Contents/MacOS/lib/libintl.8.dylib /usr/local/lib/

but it resulted the same outcome.

I am new to RHESSys and Mac. I will be very grateful if someone could solve this problem.
I am working on Mac OS X El Capitan 10.11.1, rhessys version is rhessys5.20.1, GRASS-6.4.6svn, cf10.0b3

Many many thanks in advance.

**Comment by jschoate** [comment]
Have seen some issues with the installation of GRASS on El Capitan.
Please see http://grassmac.wikidot.com/

But - it you have GRASS working fine....
how did you compile create flowpaths? did you compile cf10.0b3 from a
running GRASS terminal window? if not, then try that.

On Thu, Apr 14, 2016 at 3:25 AM, rahul1525 <notifications@github.com> wrote:

> I have been trying to run generation of flowtables for rhessys with the
> following command in the terminal-
>
> cf10.0b3 output=RHESSys/workspace/grass/flowtables/flowtable.dem
> template=RHESSys/workspace/grass/worldfiles/templates/template.txt
> stream=str100 road=zero dem=dem slope=slope cellsize=30.00000000
>
> But it resulted-
>
> dyld: Library not loaded: /usr/local/lib/libintl.8.dylib
> Referenced from:
> /Applications/GRASS-6.4.app/Contents/MacOS/lib/libgrass_gis.6.4.6svn.dylib
> Reason: image not found
> Trace/BPT trap: 5
>
> Trying to find a solution I did installed macports and even run
> sudo ln -s
> /Applications/Grass/GRASS-6.4.app/Contents/MacOS/lib/libintl.8.dylib
> /usr/local/lib/
>
> but it resulted the same outcome.
>
> I am new to RHESSys and Mac. I will be very grateful if someone could
> solve this problem.
> I am working on Mac OS X El Capitan 10.11.1, rhessys version is
> rhessys5.20.1, GRASS-6.4.6svn, cf10.0b3
>
> Many many thanks in advance.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/91>
>



-- 
Tague Team Lab Manager
1005 Bren Hall
UCSB, Santa Barbara, CA.

**Comment by rahul1525** [comment]
@jschoate, Thanks but GRASS is working fine, cf10.0b3 has been installed in the system using the command make in the terminal by going into the directory.
I follow the local installation steps posted in the wiki link of the github after dowloading the zip file of rhessys from github.

**Comment by ejhanan** [comment]
I had a lot of issues when I updated to El Capitan. One thing that helped me was to add usr/local/lib to the PATH in my bash profile.

**Comment by rahul1525** [comment]
@ejhanan, let me try that tomorrow, now the office is close in India. Thanks all for your concern I am hoping to see my problem being solved by tomorrow.

**Comment by rahul1525** [comment]
@ejhanan I tried after adding usr/local/lib to the path in my bash profile but it resulted in same result.
Can you write me down the PATH's line for me, I am confused

**Comment by rahul1525** [comment]
Hello everyone, I don't know how it is possible, but it happens that my problem is solved.?
I removed all the RHESSys executable programs from my working directory and installed again all the programs from the grass terminal. It works well and so I am closing this issue.
Thank you all for your support.
