### ISSUE TITLE
cannot create world file

### ISSUE THREAD

**Issue by rahul1525** [RHESSys/RHESSys#94]
the command is-

GRASS 6.4.4 (map):~ > g2w -w RHESSys/workspace/grass/worldfiles/world.dem -t RHESSys/workspace/grass/worldfiles/templates/templates.txt

The result is 

error: Expecting "_".

I checked the template file and it has "_" in all-----    _basin, _hillslope, _zone, _patch, _stratum.

Can anybody help me?
Thanks in advance

**Comment by Ayanava-23556003** [comment]
how did you solve this?
can you help me please!?
